# Generated by Django 4.2.7 on 2023-11-23 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroArticulos', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaRestaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCategoriaRestaurante', models.CharField(max_length=50)),
                ('imagen', models.ImageField(upload_to='imagenes_categoria_restaurante')),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreUsuario', models.CharField(max_length=50)),
                ('apellidoUsuario', models.CharField(max_length=50)),
                ('fechaNacimiento', models.DateTimeField()),
                ('direccion', models.TextField()),
                ('email', models.TextField()),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppBamp.ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreRestaurante', models.CharField(max_length=50)),
                ('categoriaRestaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppBamp.categoriarestaurante')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=600)),
                ('precio', models.IntegerField()),
                ('nombreProducto', models.CharField(max_length=50)),
                ('carta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppBamp.carta')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importePedido', models.IntegerField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppBamp.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='categoriarestaurante',
            name='ciudades',
            field=models.ManyToManyField(to='AppBamp.ciudad'),
        ),
        migrations.AddField(
            model_name='carta',
            name='restaurante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppBamp.restaurante'),
        ),
    ]
