# Generated by Django 4.2.7 on 2023-12-01 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppBamp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='carta',
        ),
        migrations.AddField(
            model_name='producto',
            name='restaurante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AppBamp.restaurante'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Carta',
        ),
    ]
