# Generated by Django 4.2.7 on 2023-12-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBamp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='direccion',
            field=models.CharField(default='Sin dirección establecida', max_length=255),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='hAperturaRestaurante',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='hCierreRestaurante',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurante',
            name='telefono',
            field=models.CharField(default='Sin teléfono', max_length=255),
        ),
    ]
