# Generated by Django 4.2.7 on 2023-12-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBamp', '0002_restaurante_direccion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='descripcion',
            field=models.CharField(default='Sin descripción', max_length=255),
        ),
    ]
