# Generated by Django 4.2.7 on 2023-12-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBamp', '0002_remove_producto_carta_producto_restaurante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='productos',
            field=models.ManyToManyField(to='AppBamp.producto'),
        ),
    ]
