# Generated by Django 4.2.7 on 2023-12-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBamp', '0003_restaurante_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurante',
            name='imagen',
            field=models.ImageField(default='sin_imagen.png', upload_to='restaurantes/imagenes/'),
        ),
    ]
