# Generated by Django 4.2.7 on 2023-12-03 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AppBamp', '0003_pedido_productos'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaNacimiento', models.DateTimeField()),
                ('direccion', models.TextField()),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppBamp.ciudad')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppBamp.perfilusuario'),
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
