# Generated by Django 4.2.7 on 2023-11-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBamp', '0004_alter_categoriarestaurante_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriarestaurante',
            name='ciudades',
            field=models.ManyToManyField(related_name='categoriarestaurante', to='AppBamp.ciudad'),
        ),
    ]
