# Generated by Django 4.2.7 on 2023-12-03 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBamp', '0005_alter_perfilusuario_fechanacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='fechaNacimiento',
            field=models.DateField(blank=True),
        ),
    ]
