# Generated by Django 4.2.7 on 2023-12-07 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppBamp', '0005_alter_producto_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriarestaurante',
            name='ciudades',
        ),
        migrations.AddField(
            model_name='restaurante',
            name='ciudad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AppBamp.ciudad'),
            preserve_default=False,
        ),
    ]
