# Generated by Django 4.2.7 on 2023-11-15 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBamp', '0005_categoriarestaurante_ciudades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='CategoriaRestauranteCiudad',
        ),
    ]
