# Generated by Django 4.2.7 on 2023-12-03 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBamp', '0006_alter_perfilusuario_fechanacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='ciudad',
        ),
    ]
