# Generated by Django 4.2.7 on 2023-12-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBamp', '0006_remove_categoriarestaurante_ciudades_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='restaurante',
        ),
        migrations.AddField(
            model_name='producto',
            name='restaurante',
            field=models.ManyToManyField(to='AppBamp.restaurante'),
        ),
    ]
