# Generated by Django 4.2.7 on 2023-12-04 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppBamp', '0007_remove_perfilusuario_ciudad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='importePedido',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='fechaNacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PedidoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppBamp.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppBamp.producto')),
            ],
            options={
                'unique_together': {('pedido', 'producto')},
            },
        ),
        migrations.AlterField(
            model_name='pedido',
            name='productos',
            field=models.ManyToManyField(through='AppBamp.PedidoProducto', to='AppBamp.producto'),
        ),
    ]
