# Generated by Django 4.2.7 on 2023-11-09 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCarta', models.CharField(max_length=5)),
                ('numeroArticulos', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaRestaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCategoriaRestaurante', models.CharField(max_length=5)),
                ('nombreCategoriaRestaurante', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPedido', models.CharField(max_length=5)),
                ('importePedido', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUsuario', models.CharField(max_length=5)),
                ('nombreUsuario', models.CharField(max_length=50)),
                ('apellidoUsuario', models.CharField(max_length=50)),
                ('fechaNacimiento', models.DateTimeField()),
                ('direccion', models.TextField()),
                ('email', models.TextField()),
                ('nombreCiudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppBamp.ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idRestaurante', models.CharField(max_length=5)),
                ('nombreRestaurante', models.CharField(max_length=50)),
                ('idCategoriaRestaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppBamp.categoriarestaurante')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idProducto', models.CharField(max_length=5)),
                ('nombreProducto', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=600)),
                ('precio', models.IntegerField()),
                ('idCarta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppBamp.carta')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppBamp.pedido')),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppBamp.producto')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='idUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppBamp.usuario'),
        ),
        migrations.CreateModel(
            name='CategoriaRestauranteCiudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCategoriaRestaurante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppBamp.categoriarestaurante')),
                ('nombreCiudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppBamp.ciudad')),
            ],
        ),
        migrations.AddField(
            model_name='carta',
            name='idRestaurante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppBamp.restaurante'),
        ),
    ]
